#!/bin/bash

# Script to create secrets for Kafka TLS certificates
# This script generates self-signed certificates for local development

set -e

SECRETS_DIR="secrets"
DAYS_VALID=365

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "Creating secrets directory and generating TLS certificates..."

# Create secrets directory if it doesn't exist
mkdir -p "$SECRETS_DIR"

# Function to generate self-signed certificate
generate_cert() {
    local name=$1
    local cert_file="$SECRETS_DIR/${name}_cert.pem"
    local key_file="$SECRETS_DIR/${name}_key.pem"
    local ca_file="$SECRETS_DIR/${name}_ca.pem"

    echo -e "${YELLOW}Generating $name certificates...${NC}"

    # Generate CA private key and certificate
    openssl genrsa -out "$SECRETS_DIR/${name}_ca_key.pem" 2048 2>/dev/null
    openssl req -new -x509 -days "$DAYS_VALID" -key "$SECRETS_DIR/${name}_ca_key.pem" -out "$ca_file" -subj "/CN=${name}-ca/O=Development/C=US" 2>/dev/null

    # Generate server private key
    openssl genrsa -out "$key_file" 2048 2>/dev/null

    # Generate certificate signing request
    openssl req -new -key "$key_file" -out "$SECRETS_DIR/${name}_csr.pem" -subj "/CN=${name}/O=Development/C=US" 2>/dev/null

    # Sign the certificate with CA
    openssl x509 -req -days "$DAYS_VALID" -in "$SECRETS_DIR/${name}_csr.pem" -CA "$ca_file" -CAkey "$SECRETS_DIR/${name}_ca_key.pem" -CAcreateserial -out "$cert_file" 2>/dev/null

    # Remove intermediate files
    rm -f "$SECRETS_DIR/${name}_csr.pem" "$SECRETS_DIR/${name}_ca_key.pem" "$SECRETS_DIR/${name}_ca.srl"

    echo -e "${GREEN}✓ $name certificates created:${NC}"
    echo "  - Certificate: $cert_file"
    echo "  - Key: $key_file"
    echo "  - CA: $ca_file"
}

# Check if openssl is available
if ! command -v openssl &> /dev/null; then
    echo -e "${RED}Error: OpenSSL is not installed. Please install OpenSSL to generate certificates.${NC}"
    exit 1
fi

# Generate Kafka certificates
generate_cert "kafka"
echo ""

# Create a README in the secrets directory
cat > "$SECRETS_DIR/README.md" << 'EOF'
# Secrets Directory

This directory contains TLS certificates and other secrets for local development.

**WARNING: Do not commit files in this directory to git!**

The `.gitignore` file is configured to ignore all files in this directory except this README.

## Generated Files

### Kafka Certificates
- `kafka_cert.pem` - Kafka client/server certificate
- `kafka_key.pem` - Kafka private key
- `kafka_ca.pem` - Kafka Certificate Authority

## Environment Variables

Update your `.env` file with the correct paths:

```env
# Kafka TLS configuration
KAFKA_TLS_CERT_FILE=./secrets/kafka_cert.pem
KAFKA_TLS_KEY_FILE=./secrets/kafka_key.pem
KAFKA_TLS_CA_FILE=./secrets/kafka_ca.pem
```

## Production Use

For production environments:
1. Obtain certificates from a trusted Certificate Authority (CA)
2. Store certificates securely (e.g., HashiCorp Vault, AWS Secrets Manager, Kubernetes Secrets)
3. Do not use self-signed certificates generated by this script in production
EOF

echo -e "${GREEN}✓ All secrets created successfully!${NC}"
echo ""
echo "The following files were created in $SECRETS_DIR/:"
ls -la "$SECRETS_DIR"/*.pem 2>/dev/null || true
echo ""
echo -e "${YELLOW}Note: Update your .env file to use these certificates:${NC}"
echo "  KAFKA_TLS_CERT_FILE=./secrets/kafka_cert.pem"
echo "  KAFKA_TLS_KEY_FILE=./secrets/kafka_key.pem"
echo "  KAFKA_TLS_CA_FILE=./secrets/kafka_ca.pem"